name: Test and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: pip install -r src/requirements.txt

    - name: Test con Pytest
      # working-directory: src
      env:
        PYTHONPATH: src
      run: pytest test.py